"""
This module is to simply help with having a consistent namespace across the resources
"""

STACK = 'CdkEmbeddingProcessor'

ECR_STACK = 'ECR'
ECR_STACK_IMAGE = f'{STACK}-{ECR_STACK}-Image'

VPC_STACK = 'VPC'
VPC_STACK_VPC = f'{STACK}-{VPC_STACK}-Vpc'
VPC_STACK_PUBLIC_SUBNET = f'{STACK}-{VPC_STACK}-Public'
VPC_STACK_PRIVATE_SUBNET = f'{STACK}-{VPC_STACK}-Private'

BATCH_JOB_QUEUE=f'{STACK}-BatchJobQueue'
BATCH_JOB_DEFINITION=f'{STACK}-BatchJobDefinition'
BATCH_JOB_COMPUTE=f'{STACK}-BatchJobCompute'
BATCH_JOB_NAME=f'{STACK}-BatchJob'

EVENT_BRIDGE_SCHEDULER_NAME=f'{STACK}-BuildIndex'
EVENT_BRIDGE_EXECUTION_ROLE=f'{STACK}-EventBridgeBatchExecutionRole'

AOSS_SECURITYLAKE_COLLECTION=f'{STACK}-AOSS-SecurityLakeCollection'
AOSS_SECURITYLAKE_ENCRYPTION_POLICY=f'{STACK}-AOSS-EncryptionPolicy'
AOSS_SECURITYLAKE_NETWORK_POLICY=f'{STACK}-AOSS-NetworkPolicy'
AOSS_SECURITYLAKE_DATA_ACCESS_POLICY=f'{STACK}-AOSS-DataAccessPolicy'
AOSS_SECURITYLAKE_READ_ONLY_DATA_ACCESS_POLICY=f'{STACK}-AOSS-ReadOnlyDataAccessPolicy'
AOSS_OUTPUT_COLLECTION_ENDPOINT=f'{STACK}-CollectionEndpoint'
AOSS_OUTPUT_DASHBOARD_ENDPOINT=f'{STACK}-DashboardEndpoint'

IAM_TASK_EXECUTION_ROLE=f'{STACK}-TaskExecutionRole'

ECR_REPO_IMAGE_NAME=f'{STACK}-ProcessorImage'

S3_ATHENA_BUCKET=f'{STACK}-S3AthenaBucket'

LAKE_FORMATION_PERMISSION=f'{STACK}-CfnPrincipalPermissions'
LAKE_FORMATION_SETTINGS=f'{STACK}-LakeFormatinSettings'