# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0



# stack resource ids/names
STACK = 'CybersecurityGenAIDemo'
STACK_DESCRIPTION = 'Cybersecurity GenAI Demo'

# authentication
AUTHENTICATION_STACK = 'Authentication'
USER_POOL_ID = 'CognitoUserPool'
USER_POOL_NAME = STACK
USER_POOL_CLIENT_ID = 'CognitoApplicationClient'
USER_POOL_CLIENT_NAME = 'WebUI'
IDENTITY_POOL_ID = 'CognitoIdenityPool'
IDENTITY_POOL_NAME = STACK
IDENTITY_POOL_IAM_POLICY_ID = 'CognitoIdenityPoolIamPolicy'
IDENTITY_POOL_IAM_POLICY_NAME = f'{STACK}-IdentityPool-Policy'

# web ui
WEB_UI_STACK = 'WebSite'
WEB_UI_S3_BUCKET_ID = 'WebUiBucket'
WEB_UI_S3_BUCKET_NAME = (f'{STACK}-WebUi').lower()
CLOUDFRONT_DISRTIBUTION_ID = 'CloudFrontDistribution'
CLOUDFRONT_DISTRIBUTION_COMMENT = f'Hosts the web ui for {STACK}'
CLOUDFRONT_CACHE_POLICY_ID = 'CloudFrontCachePolicy'
CLOUDFRONT_CACHE_POLICY_NAME = f'{STACK}-CacheDisabled'

# search security lake
SEARCH_SECURITY_LAKE_STACK = 'SearchSecurityLake'
SEARCH_SECURITY_LAKE_PARAMETER_ID = 'SSMParameter'
SEARCH_SECURITY_LAKE_PARAMETER_NAME = f'{SEARCH_SECURITY_LAKE_STACK}-Parameter'
SEARCH_SECURITY_LAKE_LAMBDA_ID = 'LambdaFunction'
SEARCH_SECURITY_LAKE_LAMBDA_NAME = f'{SEARCH_SECURITY_LAKE_STACK}-Function'
SEARCH_SECURITY_LAKE_LAMBDA_DESCRIPTION = 'Query OpenSearch on behalf of Bedrock Agents.'
SEARCH_SECURITY_LAKE_LAMBDA_IAM_POLICY_ID = 'LambdaIamPolicy'
SEARCH_SECURITY_LAKE_LAMBDA_IAM_POLICY_NAME = f'{SEARCH_SECURITY_LAKE_STACK}-LambdaPolicy'
SEARCH_SECURITY_LAKE_LAMBDA_IAM_ROLE_ID = 'LambdaIamRole'
SEARCH_SECURITY_LAKE_LAMBDA_IAM_ROLE_NAME = f'{SEARCH_SECURITY_LAKE_STACK}-LambdaRole'
SEARCH_SECURITY_LAKE_LAMBDA_LAYER_BOTO3_ID = 'LambdaLayerBoto3'
SEARCH_SECURITY_LAKE_LAMBDA_LAYER_BOTO3_NAME = 'LambdaLayerBoto3'
SEARCH_SECURITY_LAKE_LAMBDA_LAYER_OPENSEARCHPY_ID = 'LambdaLayerOpenSearchPy'
SEARCH_SECURITY_LAKE_LAMBDA_LAYER_OPENSEARCHPY_NAME = 'LambdaLayerOpenSearchPy'

# cybersecurity genai Agent
BEDROCK_AGENT_STACK = 'CybersecurityAgent'
BEDROCK_AGENT_ID = 'BedrockAgent'
BEDROCK_AGENT_NAME = 'CybersecurityAgent'
BEDROCK_AGENT_DESCRIPTION = 'Demo of a Bedrock Agent that uses Generative AI to provide insights from Amazon Security Lake.'
BEDROCK_AGENT_ALIAS_ID = 'BedrockAgentAlias'
BEDROCK_AGENT_ALIAS_NAME = 'Live'
BEDROCK_AGENT_ALIAS_DESCRIPTION = 'Current Live Version.'
BEDROCK_AGENT_IAM_POLICY_ID = 'BedrockAgentIamPolicy'
BEDROCK_AGENT_IAM_POLICY_NAME = f'{BEDROCK_AGENT_STACK}-BedrockAgentPolicy'
BEDROCK_AGENT_IAM_ROLE_ID = 'BedrockAgentIamRole'
BEDROCK_AGENT_IAM_ROLE_NAME = f'{BEDROCK_AGENT_STACK}-BedrockAgentRole'
